### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by wojtek-krysiak** [SoftwareBrothers/better-docs#10]
- prettify theme picker
  - `npm` install `color-themes-for-google-code-prettify` as a dependency
    - provide a default theme (tomorrow-dark?)
    - once the selection is chosen write the stylesheet to the current directory and provide instructions for including the stylesheet in the jsdoc configuration file `betterDocs.prettifyTheme`?
- `eject` functionality akin to `create-react-app` (post v2.0.0)
  - loads the templates, source files, and plugins into the user's directory.
  - This is just an idea, and one that I'm not completely sold on yet.
- hot reload server for doc development

**Comment by JustinBeaudry** [comment]
> hot reload server for doc development

Is being handled in https://github.com/SoftwareBrothers/better-docs/issues/11
