### ISSUE TITLE
404 for all pages when viewing

### ISSUE THREAD

**Issue by inviscid** [SoftwareBrothers/better-docs#101]
**Symptom**

All better-doc managed pages are appearing with a 404.
Permalink address shown when editing the doc page matches exactly.

**Recent Change**
We recently decided to change the path from "docs" to "documentation" which caused the 404s to start.  Changing back to "docs" doesn't fix the problem.

It seems the better docs routing process has become disconnected from WP somehow.  WP seems unaware the pages exist and raises a 404 each time.

Our users are now unable to access any documentation at the moment but there does not seem to be a clear path to fix this.

**Comment by wojtek-krysiak** [comment]
i think that you posted an issue to the wrong repo :) it is not better docs for wordpress
