### ISSUE TITLE
Representation of jsdoc "parameters with properties"

### ISSUE THREAD

**Issue by paolodina** [SoftwareBrothers/better-docs#104]
Hi, I'm documenting a class using [parameters with properties](https://jsdoc.app/tags-param.html#parameters-with-properties) syntax.

```
/**
   * Register a new user.
   *
   * @param user { Object } User
   * @param user.email { string } User email
   * @param user.password { string } User password
   * @param user.profile { Object } User profile
   *   @param user.profile.displayName {string} User profile: display name
   *   @param user.profile.firstName {string} User profile: first name
   *   @param user.profile.lastName {string} User profile: last name
   */
```
I noted that the default template, no offence, gives a more clear visualization of such jsdoc because of the visual nesting.

This:
![Screenshot_2020-09-17_09-55-46](https://user-images.githubusercontent.com/1157401/93438069-0e4af900-f8cd-11ea-9bc3-7f5c85a5d8a0.png)

Versus:
![Screenshot_2020-09-17_09-56-38](https://user-images.githubusercontent.com/1157401/93438118-2753aa00-f8cd-11ea-8d33-67c6e60e762f.png)

Can I change something to have the same effect with better-docs (which btw is awesome)?

**Comment by paolodina** [comment]
Well, better-docs should support this, in fact it provides `deep-level-*` classes.

I just don't know how to make the last three items to be recognized as `deep-level-2`. I could be an issue in my syntax, but the same syntax works well with the default template.

![Screenshot_2020-09-18_10-31-41](https://user-images.githubusercontent.com/1157401/93575759-4ec47880-f99a-11ea-8c50-4c3330d9565f.png)

Any help?

**Comment by wojtek-krysiak** [comment]
i think it was rewritten comparing the default template. You can modify the tmpl files locally in your node_modules/better-docs folder
