### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by wojtek-krysiak** [SoftwareBrothers/better-docs#11]
## Dogfooding/Example <span id="example"></span>
i.e., host docs for `better-docs` on a JSDoc generated Github Pages site using the `better-docs` theme. This is a great way to demonstrate `better-docs` without having to use the admin tool you built.

**Comment by JustinBeaudry** [comment]
I've set up several npm scripts for the development workflow. 

* watch function to re/generate docs on code-base change
* watch function to generate docs on doc source change

**Comment by JustinBeaudry** [comment]
I just noticed that https://github.com/SoftwareBrothers/better-docs/issues/10 has a line item that I've been handling under this ticket.

> hot reload server for doc development
