### ISSUE TITLE
Does this library use Typescript type inference?

### ISSUE THREAD

**Issue by cowwoc** [SoftwareBrothers/better-docs#111]
If I run better-docs against my Typescript library where the latter infers a function's return type, do I need to repeat myself by explicitly specifying the return type in JSDoc? Or is bettter-docs smart enough to use Typescript's inference to pick up these types automatically?

**Comment by wojtek-krysiak** [comment]
you will have to repeat. better-docs right now handles only types and interfaces in the way you described.

We have plans to change that but I thin it will happen next year (we will have to get rid of jsdoc dependency and write that on our own)

**Comment by cowwoc** [comment]
@wojtek-krysiak You talked about types and interfaces. What about classes? Specifically, what about class methods?

**Comment by wojtek-krysiak** [comment]
the same - you will have to write  `/** @param {type} name description` manually.
