### ISSUE TITLE
Description style not applied

### ISSUE THREAD

**Issue by zadvorsky** [SoftwareBrothers/better-docs#12]
Hi there.

I came across this repo though the category tag. Thanks for setting it up.

When I generate my docs, the description style doesn't get applied properly. On the [example docs](https://softwarebrothers.github.io/admin-bro-dev/index.html), the descriptions get style from the [member.sass style](https://github.com/SoftwareBrothers/better-docs/blob/master/styles/components/member.sass#L29-L32).

In my generated docs, this style doesn't get applied because the description isn't wrapped in a `<p>` tag, but injected straight into the div. See the two attached screenshots.

Is this a problem with the template? My comments look the same as the in the example repo.

![example](https://user-images.githubusercontent.com/1788990/54718933-0d97a200-4b32-11e9-9be2-33c2f50a5e75.png)
![mine](https://user-images.githubusercontent.com/1788990/54718934-0d97a200-4b32-11e9-95b9-14414e3c0a87.png)

**Comment by wojtek-krysiak** [comment]
Probably it is a problem with a template. Please let me know which JSDoc tag causes this and where you use it (snippet of code). I will try to recreate that and fix it. PS. Maybe you could also send a screenshot of the page with the styling problem?
