### ISSUE TITLE
Missing a space with optional parameters in class signature

### ISSUE THREAD

**Issue by lqmanh** [SoftwareBrothers/better-docs#13]
![Screenshot_2019-03-25 JSDoc Scheduler](https://user-images.githubusercontent.com/20436482/54883736-73ba5700-4e9b-11e9-88da-853beddd044c.png)

In the screenshot above, class `Scheduler` signature should be `(abstract) Scheduler(initUrl, options opt)` (a space between `options` and `opt`), as in the constructor signature right below it.

Please fix this issue soon. Many thanks!

**Comment by wojtek-krysiak** [comment]
thanks. Will do this today.

**Comment by wojtek-krysiak** [comment]
fixed in 1.1.6 release today - check it out
