### ISSUE TITLE
change the default Home title (and also other titles)

### ISSUE THREAD

**Issue by Ektoplasme** [SoftwareBrothers/better-docs#139]
Hello,

could we add the ability to change the default Home title? 

https://github.com/SoftwareBrothers/better-docs/blob/fbcbaf6da5af257629d9254621aa08bfe580e767/publish.js#L818

Also here i get a "Title" above "Global" i don't know why
<img width="415" alt="Screenshot 2021-03-04 at 11 47 23" src="https://user-images.githubusercontent.com/20521823/109952727-75bffe00-7cdf-11eb-81eb-220308054954.png">

Also is there a way to remove or rename the default navlink "API Documentation" ?

Thanks

**Comment by kurapatijayaram** [comment]
+1

**Comment by zehuiguan** [comment]
+1

**Comment by ariansobczak-rst** [comment]
> Hello,
> 
> could we add the ability to change the default Home title?
> 
> https://github.com/SoftwareBrothers/better-docs/blob/fbcbaf6da5af257629d9254621aa08bfe580e767/publish.js#L818
> 
> Also here i get a "Title" above "Global" i don't know why <img alt="Screenshot 2021-03-04 at 11 47 23" width="415" src="https://user-images.githubusercontent.com/20521823/109952727-75bffe00-7cdf-11eb-81eb-220308054954.png">
> 
> Also is there a way to remove or rename the default navlink "API Documentation" ?
> 
> Thanks

Hi, regarding change page title you can configure it in `jsdoc.json` file e.g.
```
"templates": {
        "better-docs": {
            "title": "Your awesome page title", // HTML title
```
`Home` is added at the end to indicate the current route, here home page.

Good point with unnecessary title in the global page, it will be removed in related PR.

Regarding `API Documentation` we moved it to the configuration file as `navDocumentationLabel` default `Documentation`.

**Comment by robertozmc** [comment]
I think @Ektoplasme idea was to parametrize that hardcoded value "Home".
https://github.com/SoftwareBrothers/better-docs/blob/419d4f6aef54591d54dfef034d9d705fe72dd304/publish.js#L818
