### ISSUE TITLE
placeholder text on home page

### ISSUE THREAD

**Issue by Crow08** [SoftwareBrothers/better-docs#14]
The subtitle "Title" set in [publish.js line 660](https://github.com/SoftwareBrothers/better-docs/blob/a0a4b046f7ae77e49931338b85f125a0ae71a878/publish.js#L660) seems like a placeholder and cannot be edited. 
I would prefer an empty string or a way to set it manually.

![](https://i.imgur.com/U1gIpc0.png)

**Comment by pasupulaphani** [comment]
Still an issue
