### ISSUE TITLE
Unexpected token: punc (.)

### ISSUE THREAD

**Issue by joshuadiezmo** [SoftwareBrothers/better-docs#140]
I got `Unexpected token: punc (.)` error when i generate documentation with optional chain.

this is my sample code.
```
const stats = containerRef?.current?.getBoundingClientRect();
    setContainerWidth(stats?.width);
```

**Comment by ariansobczak-rst** [comment]
Unforunetally can't reproduce this issue. Please check on the current version [v2.7.1](https://github.com/SoftwareBrothers/better-docs/releases/tag/v2.7.1)
