### ISSUE TITLE
Repeated methods the number of files part of the same module

### ISSUE THREAD

**Issue by lemanoel** [SoftwareBrothers/better-docs#15]
I have four scripts as part of the same module:
- get.js
- geyById.js
- post.js
- putById.js

The four begin as follows:
`/**
 * Express Orders Controller
 * @category Controllers
 * @module Orders
 */`

The module page in the documentation starts correctly as follows:
![Captura de tela de 2019-06-10 09-15-46](https://user-images.githubusercontent.com/34510652/59197913-7ce4c700-8b60-11e9-82b2-7a965e6e3201.png)

But when the methods are finished, it starts again the description of all methods as in the beginning:
![Captura de tela de 2019-06-10 09-18-11](https://user-images.githubusercontent.com/34510652/59198002-b4537380-8b60-11e9-9bcc-f0e2f2b7cb69.png)

And this goes on for two more times, totaling four identical descriptions of all methods of the four files.

I'm new to jsdocs, so I'm not sure if this is what I did, having four files with the same module name is incorrect or if it's really a better-docs bug. In one way or another, I appreciate any help.

**Comment by wojtek-krysiak** [comment]
still there ? :) I think it is an jsdoc issue, since we didn't change the "core"
