### ISSUE TITLE
Components

### ISSUE THREAD

**Issue by KamMosak** [SoftwareBrothers/better-docs#16]
Hello,
In the example documentation (for AdminBro) you use @component tag to describe components and that is nice showed in sidebar (like modules, classes etc). Is this tag provided by some jsdoc's plugin? I really want to use it with my Vue.js project where I have a lot of components.

**Comment by wojtek-krysiak** [comment]
Hi - it's in development phase - we will publish the @component plugin next month (it will be integrated part of better-docs)

**Comment by madisabel** [comment]
Hi,

Do you have an update on the next version of the better-docs? @component tag support would be awesome!

**Comment by wojtek-krysiak** [comment]
the deadline is the end of this month - we postponed the release due to the vacation period. It will support both react and vue.

**Comment by wojtek-krysiak** [comment]
I've released it in version 1.2 today. It is still in beta so please test it and add issues when you spot something
