### ISSUE TITLE
Polyfill version deprecated

### ISSUE THREAD

**Issue by esabotic** [SoftwareBrothers/better-docs#172]
While trying to integrate betteer docs into my app I am getting following issue 

#13 2.800 warning better-docs > react-ace > @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.

**Comment by ariansobczak-rst** [comment]
Resolved in [v2.4.1](https://github.com/SoftwareBrothers/better-docs/releases/tag/v2.4.1)
