### ISSUE TITLE
TypeScript type annotations are not automatically used in documentation

### ISSUE THREAD

**Issue by tubbo** [SoftwareBrothers/better-docs#176]
Given the following TypeScript class definition:

```typescript
class Foo {
  name: string

  /**
    * @param name - Name of this object
    */
  constructor(name: string) {
    this.name = name
  }
}
```

The `name` param will not have its type shown in the output HTML, you need to actually write the type out in JSDoc. Not sure if this is a template problem or a JSDoc problem, but I feel like if this type isn't defined in the comments, it should be pulled from the definition of the function below.

**Comment by rottmann** [comment]
This problem still exists for me in 2.7.2
JSDOC 3.6.10
