### ISSUE TITLE
could not find a copy of typescript to link in /.../node_modules/better-docs/node_modules

### ISSUE THREAD

**Issue by rusicsemenov** [SoftwareBrothers/better-docs#187]
Hello, after the last update (2.4.1) I have received error `could not find a copy of typescript to link in /.../node_modules/better-docs/node_modules` and should delete a library, because can't install packages. 

Used: `yarn`
![image](https://user-images.githubusercontent.com/20163858/150125914-17490fee-0637-4477-8541-ee4080423670.png)

**Comment by Project-Omelet** [comment]
I have same problem...
Is there anyone to solve this problem?

**Comment by lukasz-szramko-rst** [comment]
Please try with newest version 2.7.1
