### ISSUE TITLE
Apache license template in static/scripts/prettify

### ISSUE THREAD

**Issue by Jaid** [SoftwareBrothers/better-docs#2]
There is an Apache license template in the `prettify` directory that looks more like a piece of instruction than a valid license document.

https://github.com/SoftwareBrothers/better-docs/blob/98a936d03c8415b0ce8c1c937839e0cdbd74ca8b/static/scripts/prettify/Apache-License-2.0.txt#L190

Does this belong to the `prettify` library and you are forced to include the license document this way?

**Comment by wojtek-krysiak** [comment]
I was taken from the original `default` template from jsdoc: https://github.com/jsdoc3/jsdoc/blob/master/templates/default/static/scripts/prettify/Apache-License-2.0.txt
