### ISSUE TITLE
@category not working anymore

### ISSUE THREAD

**Issue by buccfer** [SoftwareBrothers/better-docs#21]
Hi, recently I updated one of my open source libraries and the documentation changed. It seems like right now the @category label is not working anymore.

Node.js version: `10.15.3`
Npm version: `6.4.1`
better-docs `1.3.0`
jsdoc `3.6.3`

Sample code: https://github.com/buccfer/aws-cognito-express
Sample generated doc: https://buccfer.github.io/aws-cognito-express/tutorial-01-quick-start.html

Thanks!

**Comment by wojtek-krysiak** [comment]
hm - which file has @category ? (but I saw that one: https://github.com/buccfer/aws-cognito-express/commit/3a24219c25433f3c5685865b0326d51db156402a - maybe this is the case?)

**Comment by wojtek-krysiak** [comment]
and also I see that you have older version of better-docs https://github.com/buccfer/aws-cognito-express/blob/master/package.json#L49

**Comment by buccfer** [comment]
Hi @wojtek-krysiak , thanks for the quick response.

@category is here for example -> https://github.com/buccfer/aws-cognito-express/blob/master/src/lib/errors/invalid-jwt-error.js#L7

And this version https://github.com/buccfer/aws-cognito-express/blob/master/package.json#L49 is correct. It has a caret (^) so if you do an npm install you will get `1.3.0` which is the latest version.

**Comment by buccfer** [comment]
@wojtek-krysiak I see some warnings due to peer dependencies.. are they required? They are reactjs dependencies..

**Comment by wojtek-krysiak** [comment]
finally, I have more time now. I've just downloaded your repo, hit `yarn` and then `yarn docs` and "unfortunately" everything is just fine - there is an "Errors" category in the sidebar.

Can you clone the repo again and perform the same steps as I did?

Regarding the dependencies - I added @component plugin to better-docs so it can create documentation for React and Vue components - thats why you see warnings.
