### ISSUE TITLE
window.component is undefined

### ISSUE THREAD

**Issue by narendrashetty** [SoftwareBrothers/better-docs#22]
In `lib/react-wrapper.js` after executing `this.executeScript()` it creates window.component object with reference to all the components. Currently I see all of the components are `undefined`.

I've tried debugging looks like the source needs to be returned after concating.
https://github.com/SoftwareBrothers/better-docs/blob/master/lib/react-wrapper.js#L96

Something like this
```javascript
try {\n        ").concat("return ", source, "\n      }
```

**Comment by wojtek-krysiak** [comment]
could you paste here you jsdoc.json file with one example component. BTW I posted an example app with configuration which could be a good starting point: https://softwarebrothers.github.io/example-design-system/index.html
