### ISSUE TITLE
Building docs fails with vue camel case named Components

### ISSUE THREAD

**Issue by iperiago** [SoftwareBrothers/better-docs#23]
(Using the @component plugin)

When a component is imported with a camel case name in a Vue file, for instance :

`import iDownload from 'components/content/Download.vue';`

I get in `/docs/entry.js ` the corresponding line : 

`import i-download from '../src/components/content/Download.vue';`

naturally breaking everything because quotes are missing around 'i-download'

Solution : add quotes to handle this (I think rather common) use case

**Comment by wojtek-krysiak** [comment]
thanks for that comment. I fixed that in version v1.3.2. Check out an example here: https://softwarebrothers.github.io/example-design-system/dash-name.html
