### ISSUE TITLE
Mixins are not properly resolved

### ISSUE THREAD

**Issue by iperiago** [SoftwareBrothers/better-docs#24]
(using @component plugin)

When a mixin is imported like this in a Vue file : 

`import userMixin from 'components/user/mixin'`

it cannot be resolved (the script does not add `/src/` before `components/user/mixin`), generating lots of lots and errors

Strangely, there are no errors of this kind with components import like this : 

`import Profile from 'components/user/Profile'`

**Comment by wojtek-krysiak** [comment]
can you please paste component along with a mixin you want to document?
