### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by J-C-L-G** [SoftwareBrothers/better-docs#27]
Is there any plan to include search functionality in the better-doc template?, thanks for the amazing template

**Comment by wojtek-krysiak** [comment]
sorry - but I don't plan to do this - but PR welcomed :)

**Comment by K0d1Lu** [comment]
I'd like to work on it, @wojtek-krysiak can you assign this issue to me ?

**Comment by wojtek-krysiak** [comment]
@K0d1Lu no problem :)
