### ISSUE TITLE
Enhancements to Component Proptypes

### ISSUE THREAD

**Issue by BrandonDenham** [SoftwareBrothers/better-docs#29]
Started using the @component tag and was hoping there could be some new features:

Support for @ignore on a propType - sometimes certain props are connected to context/redux/hoc/etc and don't need a particular prop documented.

Ability to overwrite the prop "type" with a typedef or standard jsdoc type.  PropTypes.shape, for instance isn't specific enough for some use cases.

**Comment by wojtek-krysiak** [comment]
@BrandonDenham - we use `react-docgen` package when parsing prop types. I've upgraded it to the latest version so maybe it will have more features
