### ISSUE TITLE
Links to specific line numbers in source pages do not work

### ISSUE THREAD

**Issue by senshu** [SoftwareBrothers/better-docs#30]
As an example, the following URL shows the page containing the highlighted source code of a file `Controller.js`: https://sozi.baierouge.fr/api/Controller.js.html

Adding a URL hash to move to a specific line has no effect: https://sozi.baierouge.fr/api/Controller.js.html#line32
As a consequence, all links in the documentation that target a specific source line do not behave as expected.

The problem seems to be that `linenumber.js` runs before the source code has been highlighted.

It seems to be an issue with better-docs since the default JSDoc template works as expected.

**Comment by wojtek-krysiak** [comment]
released
