### ISSUE TITLE
Support lexical sort order for categories

### ISSUE THREAD

**Issue by thecodejunkie** [SoftwareBrothers/better-docs#4]
Hi

Could we please get support for sorting categories in lexical order? I.e if I have the following categories

```
Foo.Bar.Baz
Foo
Foo.Bar
```

then they should be presented in the following order

```
Foo
Foo.Bar
Foo.Bar.Baz
```

Thanks

**Comment by wojtek-krysiak** [comment]
Just updated the repo - check out version nr 1.1.5

**Comment by thecodejunkie** [comment]
Thanks! It works like a charm!
