### ISSUE TITLE
Interface comments are ignored...

### ISSUE THREAD

**Issue by Friedoo** [SoftwareBrothers/better-docs#40]
Single-line comments are ignored

/**
 *  Comment is fine....
 */
export interface IMyInterface {
   ...
}

/**
 *  Comment is fine too.... */
export interface IMyInterface {
   ...
}

/** Comment is ignored... */
export interface IMyInterface {
  /** this member comment also is also ignored */
  isSuccess: boolean;
}

**Comment by wojtek-krysiak** [comment]
I've fixed that - check out version better-docs@1.4.7

**Comment by Friedoo** [comment]
Thank you! :)
