### ISSUE TITLE
Imported propTypes

### ISSUE THREAD

**Issue by hollislau** [SoftwareBrothers/better-docs#44]
Hi there,

It seems the parsing only works for propTypes that are defined in the component file itself. However, if the propTypes are defined in a separate file and imported into the component file, they do not seem to get picked up. Is it possible to add support for this scenario?

**Comment by wojtek-krysiak** [comment]
We use [react-docgen](https://github.com/reactjs/react-docgen) to extract data from component - and it doesn't have this functionality :(
