### ISSUE TITLE
Version 2:  Codebase cleanup, Head optimizations, etc.

### ISSUE THREAD

**Issue by JustinBeaudry** [SoftwareBrothers/better-docs#5]
BetterDocs 2.0.0 Proposal
---

## Codebase Cleanup <span id="cleanup"></span>
- moving from jQuery to using native browser API's
  - http://youmightnotneedjquery.com/
- using `const`, and `let` vs `var`.
- removing the global state from `publish.js` and making it more functional and atomic, i.e., functions mutate, and return mutated inputs rather than altering the global state.
- remove `readme` folder, and remove images from the `README`
  - while these are nice, they take all the space above-the-fold, whereas it's always nice to have a project description in that space IMO. Demos could be provided on a jsdoc generated documentation page for the project using the project. See [Dogfooding/Example](#example) below.
- rename `static` to `public`
  - remove all code in `static`
- move `tmpl` to `public`
- create `public/assets` and put the `font-awesome` heart icon into the folder
- move `styles` to `src/styles`
- move `scripts` to `src/js`, and update to use `import` syntax for use with Rollup
- remove third-party (vendor) JavaScript, e.g., `prettify`, and use `npm`.
- Use CDN for all third-party JS, and CSS.
- introduce `preload`, and `prefetch` in the head
- remove `font-awesome` and inline the heart icon as an SVG

## Use `.scss` instead of `.sass` <span id="styles"></span>
  - It's still SASS, just a modern, more familiar version of SASS which makes contributing easier. Also, CSS is valid SCSS.
  - Using `@extend` to create base styles from which other styles can extend. This results in a performant stylesheet that renders all shared styles in single declaration blocks, and aberrant styles, i.e., one-off margin adjustments, etc. to their respective component blocks.
  - Adding `typography.scss`
    - All font-related styles integrated into a single place
  - removing third-party (vendor) CSS and use `npm` to ease the upgrade process for those vendor styles, e.g., prettify styles.

## Migrate Build <span id="build"></span>
- move from a Gulp based build system to using Rollup
- `node-sass` for building the styles.
  - `gulp-sass` plugin uses `node-sass` and is typically versions behind it. `node-sass` has a built-in CLI, so it makes it easier to stay up-to-date.
- Use `Makefile` to set up all the build tasks
  - Also willing to throw these into npm scripts. I have the `Makefile` already set up. 🤷‍♂️

## More customization options, i.e., template overrides <span id="customize"></span>
- the `layout` seems essential to keep, but maybe split that up into `header` and `footer` templates, and slim down the `layout`?
- choose which side to put the mobile menu
  - right or left
- override individual templates
  - The `default` template allows overriding the `layout`, but maybe go further and allow the customization of individual template types? The effort requires some refactoring, and ideally, the template logic would remain out of the user's hands ideally and they would handle the markup (HTML)?

## CLI
- prettify theme picker
  - `npm` install `color-themes-for-google-code-prettify` as a dependency
    - provide a default theme (tomorrow-dark?)
    - once the selection is chosen write the stylesheet to the current directory and provide instructions for including the stylesheet in the jsdoc configuration file `betterDocs.prettifyTheme`?
- `eject` functionality akin to `create-react-app` (post v2.0.0)
  - loads the templates, source files, and plugins into the user's directory.
  - This is just an idea, and one that I'm not completely sold on yet.
- hot reload server for doc development

## Dogfooding/Example <span id="example"></span>
i.e., host docs for `better-docs` on a JSDoc generated Github Pages site using the `better-docs` theme. This is a great way to demonstrate `better-docs` without having to use the admin tool you built.

I've already completed the [codebase cleanup](#cleanup), the [style migration and cleanup](#styles) as well as the [build migration](#build). Working on the CLI in the next day or so. As I mentioned on Reddit, I was going to fork this project and start anew, but if you're willing to track this as a project here on your repository that would be awesome. If so we can cut a branch from master `2.0.0`, create a `Project` (Kanban auto project setting), break these items down into individual tickets (issues), and then I can push what I have up to track against those tickets.

**Comment by wojtek-krysiak** [comment]
Ok - I am on this. 

I like all your changes, but I am thinking about the `var` to `const` | `let` and other changes you may do which requires a later version of node. 

Entire JSDoc supports Node.js 4.2.0 and later so make sure your code is compatible with that.

**Comment by JustinBeaudry** [comment]
I've been too busy this past month to finish up the work on this update. I'll be busy a few more weeks before I'll deliver. Just wanted to give a health check update.
