### ISSUE TITLE
Error with @component

### ISSUE THREAD

**Issue by n3bhmb** [SoftwareBrothers/better-docs#53]
Hi, 

I use better-docs for ReactJS with parcel and I have an issue relative to our Babel configuration. 

I use an experimental syntax "classProperties" like that:
```javascript
class Animal { 
  eat = () => {
    return this;
  };
}
```

An I have this error:
```
running: parcel build buildDocs/entry.js --out-dir buildDocs/build
🚨  /Users/ben/Documents/sources/repos/hellomybot/frontreact/src/components/CustomTable/CustomTable.jsx:79:14: Support for the experimental syntax 'classProperties' isn't currently enabled (79:15)
```

Usually this error can be corrected by using the babel plugin: `@babel/plugin-proposal-class-properties` (npm install). And with this configuration in .babelrc `{
  "plugins": ["@babel/plugin-proposal-class-properties"]
}`.

However, I don't have the access to this file. **Is it possible to edit it from the better-docs options in the jsdoc.json file?**

**Comment by wojtek-krysiak** [comment]
hmm - parcel should use your .babelrc file. Couple of questions:
1. Do you use some kind of monorepo with multipe package.json files?
2. where is your babelrc file located (in the root of your app?)

**Comment by n3bhmb** [comment]
Great, thanks!

❌**The problem** was that when creating a ReactJS application with the create-react-app command, we don't have access to the .babelrc file since it is created within the dependencies of that command. 

✅**The solution** was to create a babelrc file at the root of the app that would only be read by better-docs, so without the need to eject the webpack configuration, etc. 

So your second solution works!  👍
