### ISSUE TITLE
[Need help]How to show the method summary menu on the right in a namespace?

### ISSUE THREAD

**Issue by Sara2009** [SoftwareBrothers/better-docs#56]
There are some methods in a namespace. I want to show a menu listing all the method names on the right for quick searching. Just like below:
![image](https://user-images.githubusercontent.com/9332442/72673836-67e2f580-3aaa-11ea-8191-19e2e2b95762.png)

**Comment by wojtek-krysiak** [comment]
install to version 2.0 :) - hope this helps
