### ISSUE TITLE
Codebase Cleanup

### ISSUE THREAD

**Issue by wojtek-krysiak** [SoftwareBrothers/better-docs#6]
## Codebase Cleanup <span id="cleanup"></span>
- moving from jQuery to using native browser API's
  - http://youmightnotneedjquery.com/
- using `const`, and `let` vs `var`.
- removing the global state from `publish.js` and making it more functional and atomic, i.e., functions mutate, and return mutated inputs rather than altering the global state.
- remove `readme` folder, and remove images from the `README`
  - while these are nice, they take all the space above-the-fold, whereas it's always nice to have a project description in that space IMO. Demos could be provided on a jsdoc generated documentation page for the project using the project. See [Dogfooding/Example](#example) below.
- rename `static` to `public`
  - remove all code in `static`
- move `tmpl` to `public`
- create `public/assets` and put the `font-awesome` heart icon into the folder
- move `styles` to `src/styles`
- move `scripts` to `src/js`, and update to use `import` syntax for use with Rollup
- remove third-party (vendor) JavaScript, e.g., `prettify`, and use `npm`.
- Use CDN for all third-party JS, and CSS.
- introduce `preload`, and `prefetch` in the head
- remove `font-awesome` and inline the heart icon as an SVG

**Comment by JustinBeaudry** [comment]
I have this issue already completed, I just need to make a PR. Can you assign it to me?
