### ISSUE TITLE
category with sub categories

### ISSUE THREAD

**Issue by DreadCube** [SoftwareBrothers/better-docs#61]
Hey Guys! I am currently working with the @category tag. Is there any functionality to create subcategories?

Example:

I have the categories "t.c" and "t.c.Bootstrap". 

On the sidemenu, "t.c.Bootstrap" should be appear under "t.c" as a submenu.

Or if that isn't currently possible, is there any possibility to extend the sidemenu? Maybe with a custom sidemenu template?

**Comment by bm-stschneider** [comment]
There seems to be a @subcategory tag already if you look at the category.js it is also in the publish.js but I have no idea where it will be displayed.

**Comment by wojtek-krysiak** [comment]
we are working on v2 version (currently on v2 branch). take a look at the live example here: http://adminbro.com/Theme.html . Subctegories are after the slash (/) like `components / atoms`

**Comment by bm-stschneider** [comment]
okay so you can't have @category and @subcategory or a generic @category cannot have @subcategories yet?

**Comment by wojtek-krysiak** [comment]
it can have both
