### ISSUE TITLE
React peer dependencies (react and react-dom ^0.16.0) do not exist

### ISSUE THREAD

**Issue by faudisio** [SoftwareBrothers/better-docs#65]
The package.json lists these 2 peer dependencies:

```
"react": "^0.16.0",
"react-dom": "^0.16.0",
```

Anyway React has no version matching the specified version rule.

Looking at the release [history](https://github.com/facebook/react/releases?after=v15.0.1),  React it jumps from **0.14.8** to **15.0.1** (**16.13.0** being the current version at the time of writing).

Please fix the package.json. Thanks a lot.

**Comment by wojtek-krysiak** [comment]
:) done
