### ISSUE TITLE
Use .scss instead of .sass

### ISSUE THREAD

**Issue by wojtek-krysiak** [SoftwareBrothers/better-docs#7]
## Use `.scss` instead of `.sass` <span id="styles"></span>
  - It's still SASS, just a modern, more familiar version of SASS which makes contributing easier. Also, CSS is valid SCSS.
  - Using `@extend` to create base styles from which other styles can extend. This results in a performant stylesheet that renders all shared styles in single declaration blocks, and aberrant styles, i.e., one-off margin adjustments, etc. to their respective component blocks.
  - Adding `typography.scss`
    - All font-related styles integrated into a single place
  - removing third-party (vendor) CSS and use `npm` to ease the upgrade process for those vendor styles, e.g., prettify styles.

**Comment by JustinBeaudry** [comment]
I've got this one done as well. Just need to make a PR. Can you assign this to me?
