### ISSUE TITLE
Typescript components

### ISSUE THREAD

**Issue by Barosky** [SoftwareBrothers/better-docs#70]
I can't document typescript components.
I've tried using the both @class and @component tags, but when executing the docs compiler, no documentation is produced for *.component.ts, while for models and services the docs are compiled without problems

**Comment by wojtek-krysiak** [comment]
maybe add .tsx ?

I am also using typescript and my big JSDoc setup is here: https://github.com/SoftwareBrothers/admin-bro-dev - maybe it will help you somehow

**Comment by Barosky** [comment]
It seems that excluding .spec.ts files did the trick.
