### ISSUE TITLE
Generating documentation to copy the logo image into the output folder

### ISSUE THREAD

**Issue by crs1138** [SoftwareBrothers/better-docs#71]
I'm not sure, whether I'm asking in the right place. I'm using better-docs as the theme template for my JSDoc (well done, keep up the great work). I wonder if there is a way to achieve this.

Include a logo image in the `jsdoc.json` and have this logo to be copied into the _output_ folder so the logo is available even if the _output_ folder is then deployed onto its own webserver dedicated for documentation.

**Comment by wojtek-krysiak** [comment]
yep. Take a look at this config: https://github.com/SoftwareBrothers/admin-bro-dev/blob/master/jsdoc.json#L43 - in the docs-src/assets I have all the photos
