### ISSUE TITLE
Custom links in navigation don't seem to work

### ISSUE THREAD

**Issue by stefandesu** [SoftwareBrothers/better-docs#81]
I wanted to add some custom links in the navigation like in the example in the README, but it doesn't seem to work. Here's my configuration:

```json
{
  "templates": {
    "search": true,
    "better-docs": {
      "name": "cocoda-sdk Documentation",
      "title": "cocoda-sdk",
      "navigation": [
        {
            "label": "Github",
            "href": "https://github.com/gbv/cocoda-sdk"
        },
        {
            "label": "Cocoda Mapping Tool",
            "href": "https://github.com/gbv/cocoda"
        }
      ]
    }
  }
}
```

`name` and `title` worked, but the navigation links don't show up. Any idea what I'm doing wrong? Thanks!

**Comment by sff666** [comment]
"better-docs": {
      "name": "cocoda-sdk Documentation",
      "title": "cocoda-sdk",
      "navLinks": [
        {
            "label": "Github",
            "href": "https://github.com/gbv/cocoda-sdk"
        },
        {
            "label": "Cocoda Mapping Tool",
            "href": "https://github.com/gbv/cocoda"
        }
      ]
    }

**Comment by stefandesu** [comment]
@sff666 Thanks! I added a PR fixing the example in the README.
