### ISSUE TITLE
Error: Multiple exported component definitions found

### ISSUE THREAD

**Issue by saiallala** [SoftwareBrothers/better-docs#88]
I am trying to document a few form wrapped components. The problems arises when I tried to document these components. These wrapped components are exported with the Field component from formik. Is there a solution to this problem?

**Comment by wojtek-krysiak** [comment]
I am not familiar with formik but the rules of thumb is that you have to `export default` one component from a documented file - maybe this information will help you some how?

**Comment by saiallala** [comment]
That helps. Thanks a lot😁
