### ISSUE TITLE
More customization options

### ISSUE THREAD

**Issue by wojtek-krysiak** [SoftwareBrothers/better-docs#9]
## More customization options, i.e., template overrides <span id="customize"></span>
- the `layout` seems essential to keep, but maybe split that up into `header` and `footer` templates, and slim down the `layout`?
- choose which side to put the mobile menu
  - right or left
- override individual templates
  - The `default` template allows overriding the `layout`, but maybe go further and allow the customization of individual template types? The effort requires some refactoring, and ideally, the template logic would remain out of the user's hands ideally and they would handle the markup (HTML)?

**Comment by JustinBeaudry** [comment]
This one's exploratory and we should maybe talk about before moving it into the `2.0.0` release?

**Comment by nothingismagick** [comment]
I would like to be able to turn off the timestamp because I run JSDoc on precommit, which updates every single file even if there are no changes to the JSDoc declarations...

**Comment by lava-dukanam** [comment]
Is there a way to turn off the "View Source" button on the generated docs?
